### ISSUE TITLE
Initializing LocalTerra on Raspberry Pi 4

### ISSUE THREAD

**Issue by bslima** [terra-money/LocalTerra#17]
Trying to use LocalTerra on Raspbi 4 as a server to our testnet.

Attaching to localterra_postgres_1, localterra_terrad_1, localterra_lcd_1, localterra_oracle_1, localterra_mantle_1, localterra_fcd-api_1, localterra_fcd-collector_1
fcd-api_1        | standard_init_linux.go:219: exec user process caused: exec format error
fcd-collector_1  | standard_init_linux.go:219: exec user process caused: exec format error
lcd_1            | standard_init_linux.go:219: exec user process caused: exec format error
mantle_1         | standard_init_linux.go:219: exec user process caused: exec format error
oracle_1         | standard_init_linux.go:219: exec user process caused: exec format error

**Comment by hanjukim** [comment]
I never thought it would work on Raspberry Pi. Did it work?
