### ISSUE TITLE
TerraStation: "invalid request: must contain at least one message: failed to simulate tx"

### ISSUE THREAD

**Issue by Green7** [terra-money/LocalTerra#20]
It is impossible to use Terra Station on localterra. An attempt to transfer funds between accounts ends with a message "invalid request: must contain at least one message: failed to simulate tx".

It seems Terra Station cannot calculate transaction costs and 
POST to http://localhost:3060/txs/estimate_fee
{"base_req":{"chain_id":"localterra","memo":"","from":"terra17lmam6zguazs5q5u6z5mmx76uj63gldnse2pdp","gas":"auto","gas_prices":[{"denom":"uluna","amount":"0.150000000000000000"}],"gas_adjustment":"1.75"},"msgs":[{"type":"bank/MsgSend","value":{"from_address":"terra17lmam6zguazs5q5u6z5mmx76uj63gldnse2pdp","to_address":"terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v","amount":[{"denom":"uluna","amount":"1000000"}]}}]}

returns HTTP/1.1 500 Internal Server Error
{"error":"invalid request: must contain at least one message: failed to simulate tx"}

How do I get around it?

**Comment by hanjukim** [comment]
The error is from version conflict. Please `docker-compose rm` to remove existing docker processes and try it again.

**Comment by Green7** [comment]
> The error is from version conflict. Please `docker-compose rm` to remove existing docker processes and try it again.

it works, thank you.

**Comment by Miyou** [comment]
Hi @hanjukim. I'm getting the same error when using `terra.js 1.8.9`. Doing `docker-compose rm` did not work for me. I tried pulling the latest commit of LocalTerra, but it seems you have removed support for Col-4? On the latest commit I instead get `rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract missing a required marker export: interface_version_*: store wasm contract failed: invalid request`. Can you please tell me which commit removed support for Col-4? And is the prior commit compatible with terra.js 1.8.9? Thanks.

**Comment by hanjukim** [comment]
Please use 2.0 version of Terra.js
