### ISSUE TITLE
An error in running the docker-compose up

### ISSUE THREAD

**Issue by devJovanni12** [terra-money/LocalTerra#27]
Hi, guys. I got an error in running the docker-compose up.

![2021-07-27_11h27_58](https://user-images.githubusercontent.com/73068626/127208212-1441ae75-62c3-4f3f-ba74-a264d81177c1.png)

Could you possibly let me know how to resolve this problem.
Thank you in advance.

**Comment by hanjukim** [comment]
Can you update your docker version to latest stable version?

**Comment by hanjukim** [comment]
❯ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
