### ISSUE TITLE
Unable to run docker-compose with LocalTerra

### ISSUE THREAD

**Issue by gaohan137** [terra-money/LocalTerra#28]
After uninstalling and re-installing docker-compose, somehow still couldn't make it work with LocalTerra with the following errors:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.fcd-api: 'pull_policy'
Unsupported config option for services.fcd-collector: 'pull_policy'
Unsupported config option for services.oracle: 'pull_policy'
Unsupported config option for services.terrad: 'pull_policy'
```

My docker-compose has version: `docker-compose version 1.17.1, build unknown`

If these 'pull_policy' lines are removed, things are running just fine. Any idea why this is the case? (I also tried to inspect indentation or special characters, but didn't seem to help).

**Comment by hanjukim** [comment]
❯ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
