### ISSUE TITLE
Getting `code: 12` while trying to access LCD or FCD

### ISSUE THREAD

**Issue by tkowalczyk** [terra-money/LocalTerra#32]
After installation on WSL 2 in Ubuntu 18 I am getting following error while trying to access:

* http://localhost:3060/
* http://localhost:1317/

```
{
  "code": 12,
  "message": "Not Implemented",
  "details": [
  ]
}
```

`docker-compose --version`

![obraz](https://user-images.githubusercontent.com/1682564/128924479-f9656597-a416-4212-b6f7-cae052ef0f08.png)

**Comment by hanjukim** [comment]
@tkowalczyk It is supposed to be return code 12 from Terra Core 0.5. Not actually an error.
