### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by obnoxiousish** [terra-money/LocalTerra#42]
I was wondering if there was an easy way to setup this LocalTerra to actually be for colombus-4 and have public facing RPC / node i could use for my terra station for example. I setup my own terrad and setting up lcd/fcd with terracli being gone seems to be missing a proper guide and this looked potentially easier.

Thanks.

**Comment by Vritra4** [comment]
sorry for the late response.

the purpose of LocalTerra is `to make it easy for smart contract developers to test out their contracts on a sandboxed environment before moving to a live testnet or mainnet.` like readme.md mentioned, not to run mainnet node.

and terracli is not gone. :) just merged into terrad. you can use terrad like terracli.
