### ISSUE TITLE
Error: error unmarshalling result: unknown field "isOracleTx" in types.ResponseCheckTx

### ISSUE THREAD

**Issue by ghost** [terra-money/LocalTerra#45]
Getting Error: error unmarshalling result: unknown field "isOracleTx" in types.ResponseCheckTx
when trying to run a contract on my localterra network.

If this helps: terrad version --long
name: terra
server_name: terrad
version: 0.5.6
commit: 6e903ef290de2b9930129f069af87e3f99215065
build_tags: netgo ledger,
go: go version go1.16.8 linux/amd64

**Comment by josh-burton** [comment]
That's the version of the terra-core repo to use, not LocalTerra.

https://github.com/terra-money/core/releases/tag/v0.5.6-oracle

**Comment by ceikit** [comment]
> That's the version of the terra-core repo to use, not LocalTerra.
> 
> https://github.com/terra-money/core/releases/tag/v0.5.6-oracle

thanks Josh you are right, following your advice worked and I was able to upload the contract to LocalTerra.

However TerraStation cannot find LocalTerra anymore after switching to `core v0.5.6-oracle` - do you know why?

**Comment by shravanshetty1** [comment]
> Try again using terrad v0.5.6-oracle instead of v0.5.6



> That's the version of the terra-core repo to use, not LocalTerra.
> 
> https://github.com/terra-money/core/releases/tag/v0.5.6-oracle

Got it to work!

**Comment by ceikit** [comment]
> > Try again using terrad v0.5.6-oracle instead of v0.5.6
> 
> > That's the version of the terra-core repo to use, not LocalTerra.
> > https://github.com/terra-money/core/releases/tag/v0.5.6-oracle
> 
> Got it to work!

are you able to connect to TerraStation when running core on -oracle version?

**Comment by octalmage** [comment]
Closing this issue, the oracle branch is a thing of the past.
