### ISSUE TITLE
Exec user process caused: exec format error (MBP M1, Parallells, Ubuntu 20.04)

### ISSUE THREAD

**Issue by Aregaard** [terra-money/LocalTerra#52]
I followed the instrctions on: https://docs.terra.money/Tutorials/Smart-contracts/Set-up-local-environment.html#install-terra-core-locally

**Equipment**
HW: Apple Mac Book Pro M1 2020
SW: Ubuntu 20.04 running on Parallells
SW: Docker running on Ubuntu 20.04, which runs on Parallells

Why all the VM? Because I am pretty new to Blockchain development and want a test environment that is foolproof :)

**Question**: I get a lot of exec errors when I run `docker-compose up`. What have I missed?

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/16863326/146081685-d524d4ea-f298-4b1a-8b45-151979dbe11d.png">

When I try to install the Terra Core:

```shell-session
usr/bin/ld: skipping incompatible ../go/pkg/mod/github.com/!cosm!wasm/wasmvm@v0.16.2/api/libwasmvm.so when searching for -lwasmvm
/usr/bin/ld: cannot find -lwasmvm
collect2: error: ld returned 1 exit status
make: *** [Makefile:123: install] Error 2
```
According to the WASMER:
```shell-session
Latest release: 2.1.0
Downloading archive from https://github.com/wasmerio/wasmer/releases/download/2.1.0/wasmer-linux-aarch64.tar.gz
######################################################################## 100.0%
error: Your platform is not yet supported (linux-aarch64).
Please open an issue on the project if you would like to use wasmer in your project: https://github.com/wasmerio/wasmer
```

My conclusion is: Get a AMD64. Any input on this?

**Comment by Vritra4** [comment]
you right. ubuntu on M1 is arm-based and it is not supported.
