### ISSUE TITLE
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by popcornazerty** [terra-money/LocalTerra#56]
Every time I try to access one of my wallet  from "import private key" on terra station chrome app I get this error

Steps to reproduce:
Install terra station chrome app
import private key

Expected result:
Able to log in wallet
<img width="410" alt="Capture d’écran 2022-01-05 à 12 35 48" src="https://user-images.githubusercontent.com/78792807/148211427-e8e117c7-eefd-41a6-9214-1ce292000dea.png">

**Comment by Vritra4** [comment]
it is not related to LocalTerra. raise this issue at station repository please.
