### ISSUE TITLE
couldn't make client config: mkdir /.terra: permission denied

### ISSUE THREAD

**Issue by chaishiqi** [terra-money/LocalTerra#57]
Hi,I run it in docker, the tag is 0.5.14. My data path is /data/luna. when I execute the tx command with --home arg, like below

```
terrad tx send <key> <addr> 10000000uluna --chain-id=localterra --home /data/luna
```

the error still occurs

```
Error: couldn't make client config: mkdir /.terra: permission denied
Usage:
  terrad tx [flags]
  terrad tx [command]
```

what's the problem?

**Comment by Vritra4** [comment]
check your mount option and check /data/luna can be accessible by your account.
