### ISSUE TITLE
Object does not exist at path “/”

### ISSUE THREAD

**Issue by Haggus** [terra-money/LocalTerra#58]
I've been following the tutorial. After setting up LocalTerra, when I run `terrad keys add test1 --recover`, and enter the mnemonic, I get `Error: Object does not exist at path “/”`.

Running `./terrad keys list` returns `[]`.

It looks like accounts were not migrated? Is there an additional step I need to execute?

**Comment by Vritra4** [comment]
do without `--recover` please.
accounts are not in your local keychain.
