### ISSUE TITLE
Arch terramoney/pseudo-feeder:0.5.5

### ISSUE THREAD

**Issue by janfabian** [terra-money/LocalTerra#63]
Hi, I've got trouble running local oracle on my linux/amd64 arch. 

```
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

When I check the docker hub image for version terramoney/pseudo-feeder:0.5.5, I see the only arch `linux/arm64`. Is it desired?

**Comment by hanjukim** [comment]
No, I am checking it now.

**Comment by hanjukim** [comment]
Which environment do you have @janfabian ? I have no trouble with the latest commit

> oracle_1         | vote_period: 2, txhash: C39B4DCBAD0A4C21C388BE000309D7472F193EB7B4994E8E9D270C3E6A7D155A

**Comment by hanjukim** [comment]
@janfabian I pushed a new image to be consistent. https://hub.docker.com/layers/terramoney/pseudo-feeder/0.5.5/images/sha256-2967a333ddee181a3f08063db31c43403ab0f7ae9820099981944c30498ef26e?context=explore

Please do `docker pull terramoney/pseudo-feeder:0.5.5` and retry

**Comment by janfabian** [comment]
@hanjukim thanks a lot, now it works 

regarding my env 
```
  Operating System: Ubuntu 20.04.3 LTS
            Kernel: Linux 5.13.0-28-generic
      Architecture: x86-64
```
