### ISSUE TITLE
Unable to see any coin besides Luna

### ISSUE THREAD

**Issue by dakom** [terra-money/LocalTerra#64]
![image](https://user-images.githubusercontent.com/6406986/156356386-973eee18-2fb5-4ae4-ab59-8a0c41294166.png)

This happens with the latest repo on both Windows and Ubuntu, so I don't think it's a host env problem

**Comment by dakom** [comment]
Note that also when going to swap, no other coins show

**Comment by dakom** [comment]
A little more info - hitting http://localhost:3060/terra/oracle/v1beta1/denoms/actives returns an empty list

**Comment by Vritra4** [comment]
is your pseudo-feeder running?

**Comment by dakom** [comment]
I wonder if it's that the explicit fee was taken out... https://github.com/terra-money/LocalTerra/commit/71d4693f99d5725e892bae66db402d2b14ed3f4c#diff-54855b3c211c1c73c2545a70b576ed8395ebb84115d405061d2f4255700e8210R136

Will see what happens if I add that back in...

**Comment by dakom** [comment]
Made a PR which fixes that. But I am still not seeing the full list. Could there be a cacheing issue, or maybe the Docker containers aren't getting it from the local build somehow? Maybe once the PR is merged and the version is bumped it'll magically fix itself...

**Comment by Vritra4** [comment]
see https://github.com/terra-money/LocalTerra/pull/65#issuecomment-1057930208 please. 
i'll ask to merge #60.

**Comment by dakom** [comment]
Ok wth... @Vritra4 can you or someone else please explain how this makes any sense?

When I ran my PR it fixes things. Fine. Then I wipe everything:

1. all docker containers and images
2. the local directory

I then re-clone the repo, and run again (to create a failing case to test against)

And everything is working?!?!?

**Comment by Vritra4** [comment]
@dakom maybe pseudo-feeder image was different :) #60 merged anyway

**Comment by dakom** [comment]
Latest commit does *NOT* fix it for me. Fwiw I do see this in the logs, not sure if it's relevant:

```
TOKEN_NETWORK not defined in environment variable
```

**Comment by Vritra4** [comment]
@dakom still having same issue? hmm it's weird. could you and retry it after pruning docker volumes and images?
the log comes from fcd so i don't think it is related..

**Comment by dakom** [comment]
Ok, so, consider the shell script below- if I run it, sometimes I can see non-Luna currencies after things start up, sometimes I can't

When I can't, and I wait a bit, it does seem to show, but I can't guarantee that this was the case before (in the past I didn't see anything other than Luna even when waiting and coming back hours later)

If I add the `sed` command from the Readme (for faster dev time), right before `docker-compose up`, it seems to not show anything other than Luna even if I wait a bit.


```shell
#!/bin/sh
sudo rm -rf ./LocalTerra
docker container kill $(docker container ls -a -q)
docker container rm $(docker container ls -a -q)
docker image rm $(docker image ls -a -q)
docker volume rm $(docker volume ls -q)
git clone --depth 1 https://www.github.com/terra-money/LocalTerra
cd LocalTerra
docker-compose up
```

**Comment by dakom** [comment]
thanks for your help getting to the bottom of this @Vritra4 ... fwiw I can also say that none of the other devs I am in touch with directly are having this issue, which is extremely strange given that I created a fresh Ubuntu partition to investigate. In case it's relevant, I believe I followed the Docker install/setup instructions here: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04

**Comment by Vritra4** [comment]
@dakom  i think difference between app.toml(mod by sed) and pseudo-feeder causes the problem. i'll test it. thanks. :)

**Comment by octalmage** [comment]
I've seen this before when the blocktime is sped up, the feeder stops working because the commits happen too often. 

>  which is extremely strange given that I created a fresh Ubuntu partition to investigate.

Did you increase the blocktime in this new instance?

**Comment by dakom** [comment]
> Did you increase the blocktime in this new instance?

I don't think so... where is that changed?

**Comment by dakom** [comment]
(unless this is affected by the `sed` command in the README)

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)

**Comment by octalmage** [comment]
Yes! The sed is what speeds up blocktime!

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)

**Comment by Vritra4** [comment]
@dakom like @octalmage said, oracle(pseudo-feeder) doesn't work properly when the blocktime is sped up.
so i patched pseudo-feeder :) please see #70. you can test it your own docker image from the PR before the PR merged.

**Comment by dakom** [comment]
My temporary linux boxed crashed :~(

The original reason I had that was because LocalTerra wasn't working properly for me on M1, I could give that a spin again, but I'm concerned that if _that_ isn't working could be for entirely different reasons

Will update as soon as I can get around to trying LocalTerra _somewhere_ :)

**Comment by dakom** [comment]
Tried on a windows box, got a "manifest unknown" error

**Comment by Vritra4** [comment]
@dakom you need to build your own image because new pseudo-feeder is not published to docker hub yet. :)
steps i tested:
1. `docker build -t pseudofeeder .` int pseudo-feeder directory
2. update image for oracle to pseudofeeder in docker-compose.yml
4. `docker-compose up`

**Comment by hanjukim** [comment]
It is not published

**Comment by dakom** [comment]
Thanks! sorry, forgot to come back and feedback... when I switched machines I wasn't having the problem :/ 

Very much appreciate the effort in hunting down a "heisenbug" of sorts, cheers!
