### ISSUE TITLE
Managing time / block height

### ISSUE THREAD

**Issue by sealbox** [terra-money/LocalTerra#74]
Readme states that localterra is aimed for local simulation of contracts before deployment - i.e. for testing, but at the same time repository lacks the crucial information about administrative calls possible for RPC.

The information I am missing is:
- how to force localterra to mine particular amount of blocks in order to simulate "something else" hapenning on the network?
- how to force localterra to mine new block with particular timestamp in the future to simulate "passage of time"?

Both of those options would be possible with `evm_mine` instruction in Ganache for EVM. What's the couterpart for this here?

**Comment by hanjukim** [comment]
What you need is that what we are calling TestKit which is not released yet. It provides programmable way to simulate almost everything you can do in Terra blockchain.

**Comment by Mikaael1982** [comment]
> Readme states that localterra is aimed for local simulation of contracts before deployment - i.e. for testing, but at the same time repository lacks the crucial information about administrative calls possible for RPC.
> 
> The information I am missing is:
> - how to force localterra to mine particular amount of blocks in order to simulate "something else" hapenning on the network?
> - how to force localterra to mine new block with particular timestamp in the future to simulate "passage of time"?
> 
> Both of those options would be possible with `evm_mine` instruction in Ganache for EVM. What's the couterpart for this here?
