### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by tokisolou** [terra-money/LocalTerra#82]
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Useer\my-terra-dapp/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Useer\my-terra-dapp\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Useer\AppData\Local\npm-cache\_logs\2022-06-10T16_09_04_883Z-debug-0.log

**Comment by Vritra4** [comment]
it's not about LocalTerra.
