### ISSUE TITLE
Not implemented 

### ISSUE THREAD

**Issue by Starblue0** [terra-money/LocalTerra#83]
Lcd and Fcd having Not implemented issues?

Shows a code 12

![Screenshot_20220610-125641_Chrome.jpg](https://user-images.githubusercontent.com/89170602/173124312-c2954b3f-f4d4-4a4b-a3a4-0eac37c6fd2d.jpg)

Issue is the same error for local terra as well. Please fix thank you.

**Comment by Vritra4** [comment]
[terrad](http://github.com/terra-money/core) RPC node running on tcp://localhost:26657
LCD running on http://localhost:1317/
[FCD](http://www.github.com/terra-money/fcd) running on http://localhost:3060/

**Comment by Starblue0** [comment]
Yea, but no.

It's running but not implemented.

**Comment by Starblue0** [comment]
You blindly closed this issue.

**Comment by Starblue0** [comment]
This issue should not have been blindly closed. 
@Vritra4 Look atet he photo and read the issue before closing instead of skimming it.

**Comment by Starblue0** [comment]
the local LCD and lcd.terra.dev is giving a Implementation issue for the API. 

I know the network can see 1317 but it is saying it is not implemented so nothing will show. 

Go into your browser and goto it. 


https://lcd.terra.dev ~ Literally what I am talking about.

**Comment by Starblue0** [comment]
@dokwon

**Comment by Vritra4** [comment]
see https://github.com/terra-money/LocalTerra/issues/84#issuecomment-1153363845 please.
