### ISSUE TITLE
Not implemented LCD not implemented on site and local 

### ISSUE THREAD

**Issue by Starblue0** [terra-money/LocalTerra#84]
As I said Before the Local LCD and the Website showing not implemented, Actually look at the website for terra and do the local and goto the 1317 on your browser It will show the issue. 

Please goto here for ref: https://lcd.terra.dev
Shows same for Local as well. 

Stop trying to blindly close out a real issue going on with the rest client. It is causing me issues. 

In ref to this issue https://github.com/terra-money/LocalTerra/issues/83

This should not be closed blindly like a idiot, please discuss what is going on before you decide to close the issue.

**Comment by Starblue0** [comment]
@dokwon

**Comment by Vritra4** [comment]
like you said, LCD is RESTful. Just add endpoint you want to call to `https://lcd.terra.dev` like https://lcd.terra.dev/blocks/latest.
if you want to see the list of endpoints and test them, visit http://localhost:1317/swagger/ for LocalTerra.
